// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZE3udv3FjtlPxpXN4Z6eRdf43jYDu_kI',
    appId: '1:801673423003:web:52a2bb7becba5c35bd3e3e',
    messagingSenderId: '801673423003',
    projectId: 'techify-7c45b',
    authDomain: 'techify-7c45b.firebaseapp.com',
    storageBucket: 'techify-7c45b.appspot.com',
    measurementId: 'G-1RQ9X203LP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXP8hMHyHw-zpJaNKi--T2E47A4yOifxo',
    appId: '1:801673423003:android:cebdf466257d08dfbd3e3e',
    messagingSenderId: '801673423003',
    projectId: 'techify-7c45b',
    storageBucket: 'techify-7c45b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZp_XcrbLPJcgmPLrbrmlPKts2J1v6XQI',
    appId: '1:801673423003:ios:91a143782e7eb94cbd3e3e',
    messagingSenderId: '801673423003',
    projectId: 'techify-7c45b',
    storageBucket: 'techify-7c45b.appspot.com',
    iosBundleId: 'com.example.techify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZp_XcrbLPJcgmPLrbrmlPKts2J1v6XQI',
    appId: '1:801673423003:ios:91a143782e7eb94cbd3e3e',
    messagingSenderId: '801673423003',
    projectId: 'techify-7c45b',
    storageBucket: 'techify-7c45b.appspot.com',
    iosBundleId: 'com.example.techify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZE3udv3FjtlPxpXN4Z6eRdf43jYDu_kI',
    appId: '1:801673423003:web:30460a54e88c90c1bd3e3e',
    messagingSenderId: '801673423003',
    projectId: 'techify-7c45b',
    authDomain: 'techify-7c45b.firebaseapp.com',
    storageBucket: 'techify-7c45b.appspot.com',
    measurementId: 'G-SVNC75ZD1S',
  );
}
